server:
  port: 8087
spring:
  application:
    name: CourseService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courseservice
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

  resilience4j:
    circuitbreaker:
      instances:
        TeacherService:
          sliding-window-size: 10
          minimum-number-of-calls: 5
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s

        DepartmentService:
          sliding-window-size: 10
          minimum-number-of-calls: 5
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s